class BladeRunner {

    public static void main(String[] blad) {

        Blade blade1 = new Blade();
        blade1.bladeId = 1;
        blade1.brand = "Gillette";
        blade1.material = "Stainless Steel";
        blade1.length = 4.5;
        blade1.weight = 0.02;
        blade1.isSharp = true;
        System.out.println("bladeId: " + blade1.bladeId);
        System.out.println("brand: " + blade1.brand);
        System.out.println("material: " + blade1.material);
        System.out.println("length: " + blade1.length);
        System.out.println("weight: " + blade1.weight);
        System.out.println("isSharp: " + blade1.isSharp);
        System.out.println();

        Blade blade2 = new Blade();
        blade2.bladeId = 2;
        blade2.brand = "Wilkinson";
        blade2.material = "Titanium";
        blade2.length = 5.0;
        blade2.weight = 0.025;
        blade2.isSharp = true;
        System.out.println("bladeId: " + blade2.bladeId);
        System.out.println("brand: " + blade2.brand);
        System.out.println("material: " + blade2.material);
        System.out.println("length: " + blade2.length);
        System.out.println("weight: " + blade2.weight);
        System.out.println("isSharp: " + blade2.isSharp);
        System.out.println();

        Blade blade3 = new Blade();
        blade3.bladeId = 3;
        blade3.brand = "Feather";
        blade3.material = "Carbon Steel";
        blade3.length = 4.0;
        blade3.weight = 0.018;
        blade3.isSharp = true;
        System.out.println("bladeId: " + blade3.bladeId);
        System.out.println("brand: " + blade3.brand);
        System.out.println("material: " + blade3.material);
        System.out.println("length: " + blade3.length);
        System.out.println("weight: " + blade3.weight);
        System.out.println("isSharp: " + blade3.isSharp);
        System.out.println();

        Blade blade4 = new Blade();
        blade4.bladeId = 4;
        blade4.brand = "Dorco";
        blade4.material = "Platinum";
        blade4.length = 4.3;
        blade4.weight = 0.021;
        blade4.isSharp = false;
        System.out.println("bladeId: " + blade4.bladeId);
        System.out.println("brand: " + blade4.brand);
        System.out.println("material: " + blade4.material);
        System.out.println("length: " + blade4.length);
        System.out.println("weight: " + blade4.weight);
        System.out.println("isSharp: " + blade4.isSharp);
        System.out.println();

        Blade blade5 = new Blade();
        blade5.bladeId = 5;
        blade5.brand = "Astra";
        blade5.material = "Stainless Steel";
        blade5.length = 4.1;
        blade5.weight = 0.019;
        blade5.isSharp = true;
        System.out.println("bladeId: " + blade5.bladeId);
        System.out.println("brand: " + blade5.brand);
        System.out.println("material: " + blade5.material);
        System.out.println("length: " + blade5.length);
        System.out.println("weight: " + blade5.weight);
        System.out.println("isSharp: " + blade5.isSharp);
        System.out.println();

        Blade blade6 = new Blade();
        blade6.bladeId = 6;
        blade6.brand = "Laser";
        blade6.material = "Carbon Steel";
        blade6.length = 4.2;
        blade6.weight = 0.022;
        blade6.isSharp = false;
        System.out.println("bladeId: " + blade6.bladeId);
        System.out.println("brand: " + blade6.brand);
        System.out.println("material: " + blade6.material);
        System.out.println("length: " + blade6.length);
        System.out.println("weight: " + blade6.weight);
        System.out.println("isSharp: " + blade6.isSharp);
        System.out.println();

        Blade blade7 = new Blade();
        blade7.bladeId = 7;
        blade7.brand = "Shark";
        blade7.material = "Titanium";
        blade7.length = 4.7;
        blade7.weight = 0.023;
        blade7.isSharp = true;
        System.out.println("bladeId: " + blade7.bladeId);
        System.out.println("brand: " + blade7.brand);
        System.out.println("material: " + blade7.material);
        System.out.println("length: " + blade7.length);
        System.out.println("weight: " + blade7.weight);
        System.out.println("isSharp: " + blade7.isSharp);
        System.out.println();

        Blade blade8 = new Blade();
        blade8.bladeId = 8;
        blade8.brand = "SuperMax";
        blade8.material = "Platinum";
        blade8.length = 4.8;
        blade8.weight = 0.024;
        blade8.isSharp = false;
        System.out.println("bladeId: " + blade8.bladeId);
        System.out.println("brand: " + blade8.brand);
        System.out.println("material: " + blade8.material);
        System.out.println("length: " + blade8.length);
        System.out.println("weight: " + blade8.weight);
        System.out.println("isSharp: " + blade8.isSharp);
        System.out.println();

        Blade blade9 = new Blade();
        blade9.bladeId = 9;
        blade9.brand = "Persona";
        blade9.material = "Stainless Steel";
        blade9.length = 5.1;
        blade9.weight = 0.03;
        blade9.isSharp = true;
        System.out.println("bladeId: " + blade9.bladeId);
        System.out.println("brand: " + blade9.brand);
        System.out.println("material: " + blade9.material);
        System.out.println("length: " + blade9.length);
        System.out.println("weight: " + blade9.weight);
        System.out.println("isSharp: " + blade9.isSharp);
        System.out.println();

        Blade blade10 = new Blade();
        blade10.bladeId = 10;
        blade10.brand = "Derby";
        blade10.material = "Carbon Steel";
        blade10.length = 5.0;
        blade10.weight = 0.026;
        blade10.isSharp = false;
        System.out.println("bladeId: " + blade10.bladeId);
        System.out.println("brand: " + blade10.brand);
        System.out.println("material: " + blade10.material);
        System.out.println("length: " + blade10.length);
        System.out.println("weight: " + blade10.weight);
        System.out.println("isSharp: " + blade10.isSharp);
        System.out.println();

        Blade blade11 = new Blade();
        blade11.bladeId = 11;
        blade11.brand = "Kai";
        blade11.material = "Titanium";
        blade11.length = 4.6;
        blade11.weight = 0.027;
        blade11.isSharp = true;
        System.out.println("bladeId: " + blade11.bladeId);
        System.out.println("brand: " + blade11.brand);
        System.out.println("material: " + blade11.material);
        System.out.println("length: " + blade11.length);
        System.out.println("weight: " + blade11.weight);
        System.out.println("isSharp: " + blade11.isSharp);
        System.out.println();

        Blade blade12 = new Blade();
        blade12.bladeId = 12;
        blade12.brand = "Bic";
        blade12.material = "Stainless Steel";
        blade12.length = 4.4;
        blade12.weight = 0.023;
        blade12.isSharp = false;
        System.out.println("bladeId: " + blade12.bladeId);
        System.out.println("brand: " + blade12.brand);
        System.out.println("material: " + blade12.material);
        System.out.println("length: " + blade12.length);
        System.out.println("weight: " + blade12.weight);
        System.out.println("isSharp: " + blade12.isSharp);
        System.out.println();

        Blade blade13 = new Blade();
        blade13.bladeId = 13;
        blade13.brand = "Treet";
        blade13.material = "Platinum";
        blade13.length = 4.9;
        blade13.weight = 0.022;
        blade13.isSharp = true;
        System.out.println("bladeId: " + blade13.bladeId);
        System.out.println("brand: " + blade13.brand);
        System.out.println("material: " + blade13.material);
        System.out.println("length: " + blade13.length);
        System.out.println("weight: " + blade13.weight);
        System.out.println("isSharp: " + blade13.isSharp);
        System.out.println();

        Blade blade14 = new Blade();
        blade14.bladeId = 14;
        blade14.brand = "Gillette Blue";
        blade14.material = "Carbon Steel";
        blade14.length = 4.0;
        blade14.weight = 0.019;
        blade14.isSharp = false;
        System.out.println("bladeId: " + blade14.bladeId);
        System.out.println("brand: " + blade14.brand);
        System.out.println("material: " + blade14.material);
        System.out.println("length: " + blade14.length);
        System.out.println("weight: " + blade14.weight);
        System.out.println("isSharp: " + blade14.isSharp);
        System.out.println();


        Blade blade15 = new Blade();
        blade15.bladeId = 15;
        blade15.brand = "Gillette Fusion";
        blade15.material = "Titanium";
        blade15.length = 5.2;
        blade15.weight = 0.028;
        blade15.isSharp = true;
        System.out.println("bladeId: " + blade15.bladeId);
        System.out.println("brand: " + blade15.brand);
        System.out.println("material: " + blade15.material);
        System.out.println("length: " + blade15.length);
        System.out.println("weight: " + blade15.weight);
        System.out.println("isSharp: " + blade15.isSharp);
        System.out.println();

        Blade blade16 = new Blade();
        blade16.bladeId = 16;
        blade16.brand = "Lord";
        blade16.material = "Stainless Steel";
        blade16.length = 4.3;
        blade16.weight = 0.02;
        blade16.isSharp = true;
        System.out.println("bladeId: " + blade16.bladeId);
        System.out.println("brand: " + blade16.brand);
        System.out.println("material: " + blade16.material);
        System.out.println("length: " + blade16.length);
        System.out.println("weight: " + blade16.weight);
        System.out.println("isSharp: " + blade16.isSharp);
        System.out.println();

        Blade blade17 = new Blade();
        blade17.bladeId = 17;
        blade17.brand = "Trac II";
        blade17.material = "Carbon Steel";
        blade17.length = 4.1;
        blade17.weight = 0.021;
        blade17.isSharp = false;
        System.out.println("bladeId: " + blade17.bladeId);
        System.out.println("brand: " + blade17.brand);
        System.out.println("material: " + blade17.material);
        System.out.println("length: " + blade17.length);
        System.out.println("weight: " + blade17.weight);
        System.out.println("isSharp: " + blade17.isSharp);
        System.out.println();


        Blade blade18 = new Blade();
        blade18.bladeId = 18;
        blade18.brand = "Sensor Excel";
        blade18.material = "Titanium";
        blade18.length = 5.0;
        blade18.weight = 0.029;
        blade18.isSharp = true;
        System.out.println("bladeId: " + blade18.bladeId);
        System.out.println("brand: " + blade18.brand);
        System.out.println("material: " + blade18.material);
        System.out.println("length: " + blade18.length);
        System.out.println("weight: " + blade18.weight);
        System.out.println("isSharp: " + blade18.isSharp);
        System.out.println();

        Blade blade19 = new Blade();
        blade19.bladeId = 19;
        blade19.brand = "Mach3";
        blade19.material = "Platinum";
        blade19.length = 5.1;
        blade19.weight = 0.03;
        blade19.isSharp = false;
        System.out.println("bladeId: " + blade19.bladeId);
        System.out.println("brand: " + blade19.brand);
        System.out.println("material: " + blade19.material);
        System.out.println("length: " + blade19.length);
        System.out.println("weight: " + blade19.weight);
        System.out.println("isSharp: " + blade19.isSharp);
        System.out.println();

        Blade blade20 = new Blade();
        blade20.bladeId = 20;
        blade20.brand = "Edge";
        blade20.material = "Stainless Steel";
        blade20.length = 4.6;
        blade20.weight = 0.026;
        blade20.isSharp = true;
        System.out.println("bladeId: " + blade20.bladeId);
        System.out.println("brand: " + blade20.brand);
        System.out.println("material: " + blade20.material);
        System.out.println("length: " + blade20.length);
        System.out.println("weight: " + blade20.weight);
        System.out.println("isSharp: " + blade20.isSharp);
        System.out.println();


}
}
