class CasinoRunner {
    public static void main(String[] casio) {

        Casino casino1 = new Casino();
        casino1.casinoId = 1;
        casino1.name = "The Mirage";
        casino1.location = "Las Vegas";
        casino1.rating = 4.5;
        casino1.entryFee = 50.0;
        casino1.isOpen24x7 = true;
        System.out.println("casinoId: " + casino1.casinoId);
        System.out.println("name: " + casino1.name);
        System.out.println("location: " + casino1.location);
        System.out.println("rating: " + casino1.rating);
        System.out.println("entryFee: " + casino1.entryFee);
        System.out.println("isOpen24x7: " + casino1.isOpen24x7);
        System.out.println();

        Casino casino2 = new Casino();
        casino2.casinoId = 2;
        casino2.name = "Marina Bay Sands";
        casino2.location = "Singapore";
        casino2.rating = 4.7;
        casino2.entryFee = 60.0;
        casino2.isOpen24x7 = true;
        System.out.println("casinoId: " + casino2.casinoId);
        System.out.println("name: " + casino2.name);
        System.out.println("location: " + casino2.location);
        System.out.println("rating: " + casino2.rating);
        System.out.println("entryFee: " + casino2.entryFee);
        System.out.println("isOpen24x7: " + casino2.isOpen24x7);
        System.out.println();

        Casino casino3 = new Casino();
        casino3.casinoId = 3;
        casino3.name = "Bellagio";
        casino3.location = "Las Vegas";
        casino3.rating = 4.8;
        casino3.entryFee = 70.0;
        casino3.isOpen24x7 = true;
        System.out.println("casinoId: " + casino3.casinoId);
        System.out.println("name: " + casino3.name);
        System.out.println("location: " + casino3.location);
        System.out.println("rating: " + casino3.rating);
        System.out.println("entryFee: " + casino3.entryFee);
        System.out.println("isOpen24x7: " + casino3.isOpen24x7);
        System.out.println();

        Casino casino4 = new Casino();
        casino4.casinoId = 4;
        casino4.name = "Wynn Macau";
        casino4.location = "Macau";
        casino4.rating = 4.6;
        casino4.entryFee = 65.0;
        casino4.isOpen24x7 = true;
        System.out.println("casinoId: " + casino4.casinoId);
        System.out.println("name: " + casino4.name);
        System.out.println("location: " + casino4.location);
        System.out.println("rating: " + casino4.rating);
        System.out.println("entryFee: " + casino4.entryFee);
        System.out.println("isOpen24x7: " + casino4.isOpen24x7);
        System.out.println();

        Casino casino5 = new Casino();
        casino5.casinoId = 5;
        casino5.name = "Casino Lisboa";
        casino5.location = "Lisbon";
        casino5.rating = 4.2;
        casino5.entryFee = 40.0;
        casino5.isOpen24x7 = false;
        System.out.println("casinoId: " + casino5.casinoId);
        System.out.println("name: " + casino5.name);
        System.out.println("location: " + casino5.location);
        System.out.println("rating: " + casino5.rating);
        System.out.println("entryFee: " + casino5.entryFee);
        System.out.println("isOpen24x7: " + casino5.isOpen24x7);
        System.out.println();

        Casino casino6 = new Casino();
        casino6.casinoId = 6;
        casino6.name = "Venetian Macau";
        casino6.location = "Macau";
        casino6.rating = 4.9;
        casino6.entryFee = 80.0;
        casino6.isOpen24x7 = true;
        System.out.println("casinoId: " + casino6.casinoId);
        System.out.println("name: " + casino6.name);
        System.out.println("location: " + casino6.location);
        System.out.println("rating: " + casino6.rating);
        System.out.println("entryFee: " + casino6.entryFee);
        System.out.println("isOpen24x7: " + casino6.isOpen24x7);
        System.out.println();

        Casino casino7 = new Casino();
        casino7.casinoId = 7;
        casino7.name = "Crown Melbourne";
        casino7.location = "Melbourne";
        casino7.rating = 4.3;
        casino7.entryFee = 55.0;
        casino7.isOpen24x7 = false;
        System.out.println("casinoId: " + casino7.casinoId);
        System.out.println("name: " + casino7.name);
        System.out.println("location: " + casino7.location);
        System.out.println("rating: " + casino7.rating);
        System.out.println("entryFee: " + casino7.entryFee);
        System.out.println("isOpen24x7: " + casino7.isOpen24x7);
        System.out.println();

        Casino casino8 = new Casino();
        casino8.casinoId = 8;
        casino8.name = "City of Dreams";
        casino8.location = "Manila";
        casino8.rating = 4.4;
        casino8.entryFee = 50.0;
        casino8.isOpen24x7 = true;
        System.out.println("casinoId: " + casino8.casinoId);
        System.out.println("name: " + casino8.name);
        System.out.println("location: " + casino8.location);
        System.out.println("rating: " + casino8.rating);
        System.out.println("entryFee: " + casino8.entryFee);
        System.out.println("isOpen24x7: " + casino8.isOpen24x7);
        System.out.println();

        Casino casino9 = new Casino();
        casino9.casinoId = 9;
        casino9.name = "Foxwoods";
        casino9.location = "Connecticut";
        casino9.rating = 4.0;
        casino9.entryFee = 30.0;
        casino9.isOpen24x7 = true;
        System.out.println("casinoId: " + casino9.casinoId);
        System.out.println("name: " + casino9.name);
        System.out.println("location: " + casino9.location);
        System.out.println("rating: " + casino9.rating);
        System.out.println("entryFee: " + casino9.entryFee);
        System.out.println("isOpen24x7: " + casino9.isOpen24x7);
        System.out.println();

        Casino casino10 = new Casino();
        casino10.casinoId = 10;
        casino10.name = "Monte Carlo Casino";
        casino10.location = "Monaco";
        casino10.rating = 4.6;
        casino10.entryFee = 90.0;
        casino10.isOpen24x7 = false;
        System.out.println("casinoId: " + casino10.casinoId);
        System.out.println("name: " + casino10.name);
        System.out.println("location: " + casino10.location);
        System.out.println("rating: " + casino10.rating);
        System.out.println("entryFee: " + casino10.entryFee);
        System.out.println("isOpen24x7: " + casino10.isOpen24x7);
        System.out.println();
        Casino casino11 = new Casino();
        casino11.casinoId = 11;
        casino11.name = "Treasure Island";
        casino11.location = "Goa";
        casino11.rating = 4.1;
        casino11.entryFee = 1100.00;
        casino11.isOpen24x7 = true;
        System.out.println("casinoId: " + casino11.casinoId);
        System.out.println("name: " + casino11.name);
        System.out.println("location: " + casino11.location);
        System.out.println("rating: " + casino11.rating);
        System.out.println("entryFee: " + casino11.entryFee);
        System.out.println("isOpen24x7: " + casino11.isOpen24x7);
        System.out.println();

        Casino casino12 = new Casino();
        casino12.casinoId = 12;
        casino12.name = "Jackpot Junction";
        casino12.location = "Delhi";
        casino12.rating = 4.3;
        casino12.entryFee = 1300.00;
        casino12.isOpen24x7 = false;
        System.out.println("casinoId: " + casino12.casinoId);
        System.out.println("name: " + casino12.name);
        System.out.println("location: " + casino12.location);
        System.out.println("rating: " + casino12.rating);
        System.out.println("entryFee: " + casino12.entryFee);
        System.out.println("isOpen24x7: " + casino12.isOpen24x7);
        System.out.println();

        Casino casino13 = new Casino();
        casino13.casinoId = 13;
        casino13.name = "Spin Palace";
        casino13.location = "Las Vegas";
        casino13.rating = 4.7;
        casino13.entryFee = 2000.00;
        casino13.isOpen24x7 = true;
        System.out.println("casinoId: " + casino13.casinoId);
        System.out.println("name: " + casino13.name);
        System.out.println("location: " + casino13.location);
        System.out.println("rating: " + casino13.rating);
        System.out.println("entryFee: " + casino13.entryFee);
        System.out.println("isOpen24x7: " + casino13.isOpen24x7);
        System.out.println();

        Casino casino14 = new Casino();
        casino14.casinoId = 14;
        casino14.name = "Diamond Dust";
        casino14.location = "Goa";
        casino14.rating = 4.2;
        casino14.entryFee = 1250.00;
        casino14.isOpen24x7 = false;
        System.out.println("casinoId: " + casino14.casinoId);
        System.out.println("name: " + casino14.name);
        System.out.println("location: " + casino14.location);
        System.out.println("rating: " + casino14.rating);
        System.out.println("entryFee: " + casino14.entryFee);
        System.out.println("isOpen24x7: " + casino14.isOpen24x7);
        System.out.println();

        Casino casino15 = new Casino();
        casino15.casinoId = 15;
        casino15.name = "Black Pearl";
        casino15.location = "Panaji";
        casino15.rating = 3.9;
        casino15.entryFee = 1000.00;
        casino15.isOpen24x7 = true;
        System.out.println("casinoId: " + casino15.casinoId);
        System.out.println("name: " + casino15.name);
        System.out.println("location: " + casino15.location);
        System.out.println("rating: " + casino15.rating);
        System.out.println("entryFee: " + casino15.entryFee);
        System.out.println("isOpen24x7: " + casino15.isOpen24x7);
        System.out.println();

        Casino casino16 = new Casino();
        casino16.casinoId = 16;
        casino16.name = "Silver Star";
        casino16.location = "Mumbai";
        casino16.rating = 4.0;
        casino16.entryFee = 900.00;
        casino16.isOpen24x7 = false;
        System.out.println("casinoId: " + casino16.casinoId);
        System.out.println("name: " + casino16.name);
        System.out.println("location: " + casino16.location);
        System.out.println("rating: " + casino16.rating);
        System.out.println("entryFee: " + casino16.entryFee);
        System.out.println("isOpen24x7: " + casino16.isOpen24x7);
        System.out.println();

        Casino casino17 = new Casino();
        casino17.casinoId = 17;
        casino17.name = "Ruby Wheel";
        casino17.location = "Delhi";
        casino17.rating = 3.8;
        casino17.entryFee = 850.00;
        casino17.isOpen24x7 = true;
        System.out.println("casinoId: " + casino17.casinoId);
        System.out.println("name: " + casino17.name);
        System.out.println("location: " + casino17.location);
        System.out.println("rating: " + casino17.rating);
        System.out.println("entryFee: " + casino17.entryFee);
        System.out.println("isOpen24x7: " + casino17.isOpen24x7);
        System.out.println();

        Casino casino18 = new Casino();
        casino18.casinoId = 18;
        casino18.name = "Vegas Mirage";
        casino18.location = "Bangalore";
        casino18.rating = 4.4;
        casino18.entryFee = 1600.00;
        casino18.isOpen24x7 = true;
        System.out.println("casinoId: " + casino18.casinoId);
        System.out.println("name: " + casino18.name);
        System.out.println("location: " + casino18.location);
        System.out.println("rating: " + casino18.rating);
        System.out.println("entryFee: " + casino18.entryFee);
        System.out.println("isOpen24x7: " + casino18.isOpen24x7);
        System.out.println();

        Casino casino19 = new Casino();
        casino19.casinoId = 19;
        casino19.name = "Lucky Land";
        casino19.location = "Goa";
        casino19.rating = 3.6;
        casino19.entryFee = 750.00;
        casino19.isOpen24x7 = false;
        System.out.println("casinoId: " + casino19.casinoId);
        System.out.println("name: " + casino19.name);
        System.out.println("location: " + casino19.location);
        System.out.println("rating: " + casino19.rating);
        System.out.println("entryFee: " + casino19.entryFee);
        System.out.println("isOpen24x7: " + casino19.isOpen24x7);
        System.out.println();

        Casino casino20 = new Casino();
        casino20.casinoId = 20;
        casino20.name = "Jungle Jackpot";
        casino20.location = "Manali";
        casino20.rating = 4.0;
        casino20.entryFee = 1350.00;
        casino20.isOpen24x7 = true;
        System.out.println("casinoId: " + casino20.casinoId);
        System.out.println("name: " + casino20.name);
        System.out.println("location: " + casino20.location);
        System.out.println("rating: " + casino20.rating);
        System.out.println("entryFee: " + casino20.entryFee);
        System.out.println("isOpen24x7: " + casino20.isOpen24x7);
        System.out.println();
        System.out.println("MAIN ENDED");
}
}
  