 class PipeRunner {
    public static void main(String[] args) {

        Pipe pipe1 = new Pipe();
        pipe1.pipeId = 1;
        pipe1.material = "PVC";
        pipe1.diameter = 2.5;
        pipe1.length = 10;
        pipe1.color = "White";
        pipe1.usage = "Water supply";
        System.out.println("Pipe ID: " + pipe1.pipeId);
        System.out.println("Material: " + pipe1.material);
        System.out.println("Diameter: " + pipe1.diameter);
        System.out.println("Length: " + pipe1.length);
        System.out.println("Color: " + pipe1.color);
        System.out.println("Usage: " + pipe1.usage);
        System.out.println();

        Pipe pipe2 = new Pipe();
        pipe2.pipeId = 2;
        pipe2.material = "Copper";
        pipe2.diameter = 1.5;
        pipe2.length = 12;
        pipe2.color = "Brown";
        pipe2.usage = "Gas line";
        System.out.println("Pipe ID: " + pipe2.pipeId);
        System.out.println("Material: " + pipe2.material);
        System.out.println("Diameter: " + pipe2.diameter);
        System.out.println("Length: " + pipe2.length);
        System.out.println("Color: " + pipe2.color);
        System.out.println("Usage: " + pipe2.usage);
        System.out.println();

        Pipe pipe3 = new Pipe();
        pipe3.pipeId = 3;
        pipe3.material = "Steel";
        pipe3.diameter = 3.0;
        pipe3.length = 8;
        pipe3.color = "Silver";
        pipe3.usage = "Industrial";
        System.out.println("Pipe ID: " + pipe3.pipeId);
        System.out.println("Material: " + pipe3.material);
        System.out.println("Diameter: " + pipe3.diameter);
        System.out.println("Length: " + pipe3.length);
        System.out.println("Color: " + pipe3.color);
        System.out.println("Usage: " + pipe3.usage);
        System.out.println();

        Pipe pipe4 = new Pipe();
        pipe4.pipeId = 4;
        pipe4.material = "HDPE";
        pipe4.diameter = 2.0;
        pipe4.length = 15;
        pipe4.color = "Black";
        pipe4.usage = "Drainage";
        System.out.println("Pipe ID: " + pipe4.pipeId);
        System.out.println("Material: " + pipe4.material);
        System.out.println("Diameter: " + pipe4.diameter);
        System.out.println("Length: " + pipe4.length);
        System.out.println("Color: " + pipe4.color);
        System.out.println("Usage: " + pipe4.usage);
        System.out.println();

        Pipe pipe5 = new Pipe();
        pipe5.pipeId = 5;
        pipe5.material = "PEX";
        pipe5.diameter = 1.0;
        pipe5.length = 9;
        pipe5.color = "Red";
        pipe5.usage = "Heating";
        System.out.println("Pipe ID: " + pipe5.pipeId);
        System.out.println("Material: " + pipe5.material);
        System.out.println("Diameter: " + pipe5.diameter);
        System.out.println("Length: " + pipe5.length);
        System.out.println("Color: " + pipe5.color);
        System.out.println("Usage: " + pipe5.usage);
        System.out.println();

        Pipe pipe6 = new Pipe();
        pipe6.pipeId = 6;
        pipe6.material = "Iron";
        pipe6.diameter = 4.0;
        pipe6.length = 6;
        pipe6.color = "Grey";
        pipe6.usage = "Sewage";
        System.out.println("Pipe ID: " + pipe6.pipeId);
        System.out.println("Material: " + pipe6.material);
        System.out.println("Diameter: " + pipe6.diameter);
        System.out.println("Length: " + pipe6.length);
        System.out.println("Color: " + pipe6.color);
        System.out.println("Usage: " + pipe6.usage);
        System.out.println();

        Pipe pipe7 = new Pipe();
        pipe7.pipeId = 7;
        pipe7.material = "Aluminum";
        pipe7.diameter = 1.2;
        pipe7.length = 11;
        pipe7.color = "Silver";
        pipe7.usage = "Construction";
        System.out.println("Pipe ID: " + pipe7.pipeId);
        System.out.println("Material: " + pipe7.material);
        System.out.println("Diameter: " + pipe7.diameter);
        System.out.println("Length: " + pipe7.length);
        System.out.println("Color: " + pipe7.color);
        System.out.println("Usage: " + pipe7.usage);
        System.out.println();

        Pipe pipe8 = new Pipe();
        pipe8.pipeId = 8;
        pipe8.material = "Brass";
        pipe8.diameter = 0.8;
        pipe8.length = 5;
        pipe8.color = "Gold";
        pipe8.usage = "Decoration";
        System.out.println("Pipe ID: " + pipe8.pipeId);
        System.out.println("Material: " + pipe8.material);
        System.out.println("Diameter: " + pipe8.diameter);
        System.out.println("Length: " + pipe8.length);
        System.out.println("Color: " + pipe8.color);
        System.out.println("Usage: " + pipe8.usage);
        System.out.println();

        Pipe pipe9 = new Pipe();
        pipe9.pipeId = 9;
        pipe9.material = "Plastic";
        pipe9.diameter = 2.8;
        pipe9.length = 7;
        pipe9.color = "Blue";
        pipe9.usage = "Gardening";
        System.out.println("Pipe ID: " + pipe9.pipeId);
        System.out.println("Material: " + pipe9.material);
        System.out.println("Diameter: " + pipe9.diameter);
        System.out.println("Length: " + pipe9.length);
        System.out.println("Color: " + pipe9.color);
        System.out.println("Usage: " + pipe9.usage);
        System.out.println();

        Pipe pipe10 = new Pipe();
        pipe10.pipeId = 10;
        pipe10.material = "PVC";
        pipe10.diameter = 3.2;
        pipe10.length = 13;
        pipe10.color = "Grey";
        pipe10.usage = "Underground";
        System.out.println("Pipe ID: " + pipe10.pipeId);
        System.out.println("Material: " + pipe10.material);
        System.out.println("Diameter: " + pipe10.diameter);
        System.out.println("Length: " + pipe10.length);
        System.out.println("Color: " + pipe10.color);
        System.out.println("Usage: " + pipe10.usage);
        System.out.println();

        Pipe pipe11 = new Pipe();
        pipe11.pipeId = 11;
        pipe11.material = "CPVC";
        pipe11.diameter = 1.1;
        pipe11.length = 10;
        pipe11.color = "Ivory";
        pipe11.usage = "Hot Water";
        System.out.println("Pipe ID: " + pipe11.pipeId);
        System.out.println("Material: " + pipe11.material);
        System.out.println("Diameter: " + pipe11.diameter);
        System.out.println("Length: " + pipe11.length);
        System.out.println("Color: " + pipe11.color);
        System.out.println("Usage: " + pipe11.usage);
        System.out.println();

        Pipe pipe12 = new Pipe();
        pipe12.pipeId = 12;
        pipe12.material = "Steel";
        pipe12.diameter = 2.0;
        pipe12.length = 14;
        pipe12.color = "Metallic";
        pipe12.usage = "Ventilation";
        System.out.println("Pipe ID: " + pipe12.pipeId);
        System.out.println("Material: " + pipe12.material);
        System.out.println("Diameter: " + pipe12.diameter);
        System.out.println("Length: " + pipe12.length);
        System.out.println("Color: " + pipe12.color);
        System.out.println("Usage: " + pipe12.usage);
        System.out.println();

        Pipe pipe13 = new Pipe();
        pipe13.pipeId = 13;
        pipe13.material = "Copper";
        pipe13.diameter = 0.9;
        pipe13.length = 9;
        pipe13.color = "Copper";
        pipe13.usage = "Cooling system";
        System.out.println("Pipe ID: " + pipe13.pipeId);
        System.out.println("Material: " + pipe13.material);
        System.out.println("Diameter: " + pipe13.diameter);
        System.out.println("Length: " + pipe13.length);
        System.out.println("Color: " + pipe13.color);
        System.out.println("Usage: " + pipe13.usage);
        System.out.println();

        Pipe pipe14 = new Pipe();
        pipe14.pipeId = 14;
        pipe14.material = "Galvanized Iron";
        pipe14.diameter = 2.7;
        pipe14.length = 12;
        pipe14.color = "Shiny Silver";
        pipe14.usage = "Roofing";
        System.out.println("Pipe ID: " + pipe14.pipeId);
        System.out.println("Material: " + pipe14.material);
        System.out.println("Diameter: " + pipe14.diameter);
        System.out.println("Length: " + pipe14.length);
        System.out.println("Color: " + pipe14.color);
        System.out.println("Usage: " + pipe14.usage);
        System.out.println();

        Pipe pipe15 = new Pipe();
        pipe15.pipeId = 15;
        pipe15.material = "Concrete";
        pipe15.diameter = 5.0;
        pipe15.length = 20;
        pipe15.color = "Gray";
        pipe15.usage = "Sewer system";
        System.out.println("Pipe ID: " + pipe15.pipeId);
        System.out.println("Material: " + pipe15.material);
        System.out.println("Diameter: " + pipe15.diameter);
        System.out.println("Length: " + pipe15.length);
        System.out.println("Color: " + pipe15.color);
        System.out.println("Usage: " + pipe15.usage);
        System.out.println();

        Pipe pipe16 = new Pipe();
        pipe16.pipeId = 16;
        pipe16.material = "FRP";
        pipe16.diameter = 3.8;
        pipe16.length = 18;
        pipe16.color = "Green";
        pipe16.usage = "Chemical plant";
        System.out.println("Pipe ID: " + pipe16.pipeId);
        System.out.println("Material: " + pipe16.material);
        System.out.println("Diameter: " + pipe16.diameter);
        System.out.println("Length: " + pipe16.length);
        System.out.println("Color: " + pipe16.color);
        System.out.println("Usage: " + pipe16.usage);
        System.out.println();

        Pipe pipe17 = new Pipe();
        pipe17.pipeId = 17;
        pipe17.material = "Lead";
        pipe17.diameter = 1.0;
        pipe17.length = 4;
        pipe17.color = "Dull Grey";
        pipe17.usage = "Historical piping";
        System.out.println("Pipe ID: " + pipe17.pipeId);
        System.out.println("Material: " + pipe17.material);
        System.out.println("Diameter: " + pipe17.diameter);
        System.out.println("Length: " + pipe17.length);
        System.out.println("Color: " + pipe17.color);
        System.out.println("Usage: " + pipe17.usage);
        System.out.println();

        Pipe pipe18 = new Pipe();
        pipe18.pipeId = 18;
        pipe18.material = "Plastic";
        pipe18.diameter = 1.8;
        pipe18.length = 8;
        pipe18.color = "Yellow";
        pipe18.usage = "DIY plumbing";
        System.out.println("Pipe ID: " + pipe18.pipeId);
        System.out.println("Material: " + pipe18.material);
        System.out.println("Diameter: " + pipe18.diameter);
        System.out.println("Length: " + pipe18.length);
        System.out.println("Color: " + pipe18.color);
        System.out.println("Usage: " + pipe18.usage);
        System.out.println();

        Pipe pipe19 = new Pipe();
        pipe19.pipeId = 19;
        pipe19.material = "Rubber";
        pipe19.diameter = 0.5;
        pipe19.length = 3;
        pipe19.color = "Black";
        pipe19.usage = "Flexible piping";
        System.out.println("Pipe ID: " + pipe19.pipeId);
        System.out.println("Material: " + pipe19.material);
        System.out.println("Diameter: " + pipe19.diameter);
        System.out.println("Length: " + pipe19.length);
        System.out.println("Color: " + pipe19.color);
        System.out.println("Usage: " + pipe19.usage);
        System.out.println();

        Pipe pipe20 = new Pipe();
        pipe20.pipeId = 20;
        pipe20.material = "Bamboo";
        pipe20.diameter = 1.5;
        pipe20.length = 6;
        pipe20.color = "Natural";
        pipe20.usage = "Crafting";
        System.out.println("Pipe ID: " + pipe20.pipeId);
        System.out.println("Material: " + pipe20.material);
        System.out.println("Diameter: " + pipe20.diameter);
        System.out.println("Length: " + pipe20.length);
        System.out.println("Color: " + pipe20.color);
        System.out.println("Usage: " + pipe20.usage);
        System.out.println();
   }

}