class RodRunner {
    public static void main(String[] args) {

        Rod rod1 = new Rod();
        rod1.rodId = 1;
        rod1.length = 6.0;
        rod1.material = "Steel";
        rod1.usage = "Construction";
        rod1.weight = 12.5;
        rod1.brand = "TATA";
        System.out.println("Rod ID: " + rod1.rodId);
        System.out.println("Length: " + rod1.length);
        System.out.println("Material: " + rod1.material);
        System.out.println("Usage: " + rod1.usage);
        System.out.println("Weight: " + rod1.weight);
        System.out.println("Brand: " + rod1.brand);
        System.out.println();

        Rod rod2 = new Rod();
        rod2.rodId = 2;
        rod2.length = 4.5;
        rod2.material = "Aluminium";
        rod2.usage = "Electrical";
        rod2.weight = 8.2;
        rod2.brand = "Hindalco";
        System.out.println("Rod ID: " + rod2.rodId);
        System.out.println("Length: " + rod2.length);
        System.out.println("Material: " + rod2.material);
        System.out.println("Usage: " + rod2.usage);
        System.out.println("Weight: " + rod2.weight);
        System.out.println("Brand: " + rod2.brand);
        System.out.println();

        Rod rod3 = new Rod();
        rod3.rodId = 3;
        rod3.length = 5.0;
        rod3.material = "Carbon Fiber";
        rod3.usage = "Aerospace";
        rod3.weight = 3.5;
        rod3.brand = "Hexcel";
        System.out.println("Rod ID: " + rod3.rodId);
        System.out.println("Length: " + rod3.length);
        System.out.println("Material: " + rod3.material);
        System.out.println("Usage: " + rod3.usage);
        System.out.println("Weight: " + rod3.weight);
        System.out.println("Brand: " + rod3.brand);
        System.out.println();

        Rod rod4 = new Rod();
        rod4.rodId = 4;
        rod4.length = 3.0;
        rod4.material = "Brass";
        rod4.usage = "Decorative";
        rod4.weight = 6.7;
        rod4.brand = "Senco";
        System.out.println("Rod ID: " + rod4.rodId);
        System.out.println("Length: " + rod4.length);
        System.out.println("Material: " + rod4.material);
        System.out.println("Usage: " + rod4.usage);
        System.out.println("Weight: " + rod4.weight);
        System.out.println("Brand: " + rod4.brand);
        System.out.println();

        Rod rod5 = new Rod();
        rod5.rodId = 5;
        rod5.length = 2.5;
        rod5.material = "Copper";
        rod5.usage = "Grounding";
        rod5.weight = 10.4;
        rod5.brand = "Jindal";
        System.out.println("Rod ID: " + rod5.rodId);
        System.out.println("Length: " + rod5.length);
        System.out.println("Material: " + rod5.material);
        System.out.println("Usage: " + rod5.usage);
        System.out.println("Weight: " + rod5.weight);
        System.out.println("Brand: " + rod5.brand);
        System.out.println();

        Rod rod6 = new Rod();
        rod6.rodId = 6;
        rod6.length = 7.0;
        rod6.material = "Plastic";
        rod6.usage = "Toy Making";
        rod6.weight = 1.5;
        rod6.brand = "PlayPlast";
        System.out.println("Rod ID: " + rod6.rodId);
        System.out.println("Length: " + rod6.length);
        System.out.println("Material: " + rod6.material);
        System.out.println("Usage: " + rod6.usage);
        System.out.println("Weight: " + rod6.weight);
        System.out.println("Brand: " + rod6.brand);
        System.out.println();

        Rod rod7 = new Rod();
        rod7.rodId = 7;
        rod7.length = 5.5;
        rod7.material = "Titanium";
        rod7.usage = "Medical Implants";
        rod7.weight = 4.8;
        rod7.brand = "MedTech";
        System.out.println("Rod ID: " + rod7.rodId);
        System.out.println("Length: " + rod7.length);
        System.out.println("Material: " + rod7.material);
        System.out.println("Usage: " + rod7.usage);
        System.out.println("Weight: " + rod7.weight);
        System.out.println("Brand: " + rod7.brand);
        System.out.println();

        Rod rod8 = new Rod();
        rod8.rodId = 8;
        rod8.length = 6.2;
        rod8.material = "Fiberglass";
        rod8.usage = "Fishing Rod";
        rod8.weight = 2.3;
        rod8.brand = "FishMaster";
        System.out.println("Rod ID: " + rod8.rodId);
        System.out.println("Length: " + rod8.length);
        System.out.println("Material: " + rod8.material);
        System.out.println("Usage: " + rod8.usage);
        System.out.println("Weight: " + rod8.weight);
        System.out.println("Brand: " + rod8.brand);
        System.out.println();

        Rod rod9 = new Rod();
        rod9.rodId = 9;
        rod9.length = 8.0;
        rod9.material = "Iron";
        rod9.usage = "Foundation";
        rod9.weight = 15.0;
        rod9.brand = "Fe500";
        System.out.println("Rod ID: " + rod9.rodId);
        System.out.println("Length: " + rod9.length);
        System.out.println("Material: " + rod9.material);
        System.out.println("Usage: " + rod9.usage);
        System.out.println("Weight: " + rod9.weight);
        System.out.println("Brand: " + rod9.brand);
        System.out.println();

        Rod rod10 = new Rod();
        rod10.rodId = 10;
        rod10.length = 2.0;
        rod10.material = "Graphite";
        rod10.usage = "Golf Shaft";
        rod10.weight = 1.2;
        rod10.brand = "ProGolf";
        System.out.println("Rod ID: " + rod10.rodId);
        System.out.println("Length: " + rod10.length);
        System.out.println("Material: " + rod10.material);
        System.out.println("Usage: " + rod10.usage);
        System.out.println("Weight: " + rod10.weight);
        System.out.println("Brand: " + rod10.brand);
        System.out.println();

        Rod rod11 = new Rod();
        rod11.rodId = 11;
        rod11.length = 4.0;
        rod11.material = "Stainless Steel";
        rod11.usage = "Kitchen";
        rod11.weight = 5.6;
        rod11.brand = "SteelMax";
        System.out.println("Rod ID: " + rod11.rodId);
        System.out.println("Length: " + rod11.length);
        System.out.println("Material: " + rod11.material);
        System.out.println("Usage: " + rod11.usage);
        System.out.println("Weight: " + rod11.weight);
        System.out.println("Brand: " + rod11.brand);
        System.out.println();

        Rod rod12 = new Rod();
        rod12.rodId = 12;
        rod12.length = 6.5;
        rod12.material = "PVC";
        rod12.usage = "Plumbing";
        rod12.weight = 3.9;
        rod12.brand = "Finolex";
        System.out.println("Rod ID: " + rod12.rodId);
        System.out.println("Length: " + rod12.length);
        System.out.println("Material: " + rod12.material);
        System.out.println("Usage: " + rod12.usage);
        System.out.println("Weight: " + rod12.weight);
        System.out.println("Brand: " + rod12.brand);
        System.out.println();

        Rod rod13 = new Rod();
        rod13.rodId = 13;
        rod13.length = 9.0;
        rod13.material = "Wood";
        rod13.usage = "Furniture";
        rod13.weight = 10.5;
        rod13.brand = "TimberPro";
        System.out.println("Rod ID: " + rod13.rodId);
        System.out.println("Length: " + rod13.length);
        System.out.println("Material: " + rod13.material);
        System.out.println("Usage: " + rod13.usage);
        System.out.println("Weight: " + rod13.weight);
        System.out.println("Brand: " + rod13.brand);
        System.out.println();

        Rod rod14 = new Rod();
        rod14.rodId = 14;
        rod14.length = 3.3;
        rod14.material = "Bamboo";
        rod14.usage = "Crafts";
        rod14.weight = 2.0;
        rod14.brand = "NatureStick";
        System.out.println("Rod ID: " + rod14.rodId);
        System.out.println("Length: " + rod14.length);
        System.out.println("Material: " + rod14.material);
        System.out.println("Usage: " + rod14.usage);
        System.out.println("Weight: " + rod14.weight);
        System.out.println("Brand: " + rod14.brand);
        System.out.println();

        Rod rod15 = new Rod();
        rod15.rodId = 15;
        rod15.length = 7.7;
        rod15.material = "Bronze";
        rod15.usage = "Sculpture";
        rod15.weight = 9.4;
        rod15.brand = "ArtForge";
        System.out.println("Rod ID: " + rod15.rodId);
        System.out.println("Length: " + rod15.length);
        System.out.println("Material: " + rod15.material);
        System.out.println("Usage: " + rod15.usage);
        System.out.println("Weight: " + rod15.weight);
        System.out.println("Brand: " + rod15.brand);
        System.out.println();

        Rod rod16 = new Rod();
        rod16.rodId = 16;
        rod16.length = 5.8;
        rod16.material = "Zinc";
        rod16.usage = "Battery";
        rod16.weight = 4.4;
        rod16.brand = "VoltZinc";
        System.out.println("Rod ID: " + rod16.rodId);
        System.out.println("Length: " + rod16.length);
        System.out.println("Material: " + rod16.material);
        System.out.println("Usage: " + rod16.usage);
        System.out.println("Weight: " + rod16.weight);
        System.out.println("Brand: " + rod16.brand);
        System.out.println();

        Rod rod17 = new Rod();
        rod17.rodId = 17;
        rod17.length = 10.0;
        rod17.material = "Nickel";
        rod17.usage = "Electronics";
        rod17.weight = 7.8;
        rod17.brand = "PureNick";
        System.out.println("Rod ID: " + rod17.rodId);
        System.out.println("Length: " + rod17.length);
        System.out.println("Material: " + rod17.material);
        System.out.println("Usage: " + rod17.usage);
        System.out.println("Weight: " + rod17.weight);
        System.out.println("Brand: " + rod17.brand);
        System.out.println();

        Rod rod18 = new Rod();
        rod18.rodId = 18;
        rod18.length = 6.3;
        rod18.material = "Lead";
        rod18.usage = "Shielding";
        rod18.weight = 13.6;
        rod18.brand = "HeavyGuard";
        System.out.println("Rod ID: " + rod18.rodId);
        System.out.println("Length: " + rod18.length);
        System.out.println("Material: " + rod18.material);
        System.out.println("Usage: " + rod18.usage);
        System.out.println("Weight: " + rod18.weight);
        System.out.println("Brand: " + rod18.brand);
        System.out.println();

        Rod rod19 = new Rod();
        rod19.rodId = 19;
        rod19.length = 5.2;
        rod19.material = "Acrylic";
        rod19.usage = "Display";
        rod19.weight = 2.7;
        rod19.brand = "ClearRod";
        System.out.println("Rod ID: " + rod19.rodId);
        System.out.println("Length: " + rod19.length);
        System.out.println("Material: " + rod19.material);
        System.out.println("Usage: " + rod19.usage);
        System.out.println("Weight: " + rod19.weight);
        System.out.println("Brand: " + rod19.brand);
        System.out.println();

        Rod rod20 = new Rod();
        rod20.rodId = 20;
        rod20.length = 8.5;
        rod20.material = "Magnesium";
        rod20.usage = "Automotive";
        rod20.weight = 5.3;
        rod20.brand = "MagAlloy";
        System.out.println("Rod ID: " + rod20.rodId);
        System.out.println("Length: " + rod20.length);
        System.out.println("Material: " + rod20.material);
        System.out.println("Usage: " + rod20.usage);
        System.out.println("Weight: " + rod20.weight);
        System.out.println("Brand: " + rod20.brand);
        System.out.println();

}

}

