class WeaponRunner {
    public static void main(String[] args) {

        Weapon weapon1 = new Weapon();
        weapon1.weaponId = 1;
        weapon1.type = "Pistol";
        weapon1.damage = "Medium";
        weapon1.material = "Steel";
        weapon1.range = "50m";
        weapon1.isLicensed = true;
        System.out.println("Weapon ID: " + weapon1.weaponId);
        System.out.println("Type: " + weapon1.type);
        System.out.println("Damage: " + weapon1.damage);
        System.out.println("Material: " + weapon1.material);
        System.out.println("Range: " + weapon1.range);
        System.out.println("Licensed: " + weapon1.isLicensed);
        System.out.println();

        Weapon weapon2 = new Weapon();
        weapon2.weaponId = 2;
        weapon2.type = "Rifle";
        weapon2.damage = "High";
        weapon2.material = "Alloy";
        weapon2.range = "300m";
        weapon2.isLicensed = true;
        System.out.println("Weapon ID: " + weapon2.weaponId);
        System.out.println("Type: " + weapon2.type);
        System.out.println("Damage: " + weapon2.damage);
        System.out.println("Material: " + weapon2.material);
        System.out.println("Range: " + weapon2.range);
        System.out.println("Licensed: " + weapon2.isLicensed);
        System.out.println();

        Weapon weapon3 = new Weapon();
        weapon3.weaponId = 3;
        weapon3.type = "Knife";
        weapon3.damage = "Low";
        weapon3.material = "Iron";
        weapon3.range = "Close";
        weapon3.isLicensed = false;
        System.out.println("Weapon ID: " + weapon3.weaponId);
        System.out.println("Type: " + weapon3.type);
        System.out.println("Damage: " + weapon3.damage);
        System.out.println("Material: " + weapon3.material);
        System.out.println("Range: " + weapon3.range);
        System.out.println("Licensed: " + weapon3.isLicensed);
        System.out.println();

        Weapon weapon4 = new Weapon();
        weapon4.weaponId = 4;
        weapon4.type = "Sword";
        weapon4.damage = "Medium";
        weapon4.material = "Steel";
        weapon4.range = "Close";
        weapon4.isLicensed = false;
        System.out.println("Weapon ID: " + weapon4.weaponId);
        System.out.println("Type: " + weapon4.type);
        System.out.println("Damage: " + weapon4.damage);
        System.out.println("Material: " + weapon4.material);
        System.out.println("Range: " + weapon4.range);
        System.out.println("Licensed: " + weapon4.isLicensed);
        System.out.println();

        Weapon weapon5 = new Weapon();
        weapon5.weaponId = 5;
        weapon5.type = "Sniper";
        weapon5.damage = "Very High";
        weapon5.material = "Carbon Fiber";
        weapon5.range = "1000m";
        weapon5.isLicensed = true;
        System.out.println("Weapon ID: " + weapon5.weaponId);
        System.out.println("Type: " + weapon5.type);
        System.out.println("Damage: " + weapon5.damage);
        System.out.println("Material: " + weapon5.material);
        System.out.println("Range: " + weapon5.range);
        System.out.println("Licensed: " + weapon5.isLicensed);
        System.out.println();

        Weapon weapon6 = new Weapon();
        weapon6.weaponId = 6;
        weapon6.type = "Axe";
        weapon6.damage = "High";
        weapon6.material = "Iron";
        weapon6.range = "Short";
        weapon6.isLicensed = false;
        System.out.println("Weapon ID: " + weapon6.weaponId);
        System.out.println("Type: " + weapon6.type);
        System.out.println("Damage: " + weapon6.damage);
        System.out.println("Material: " + weapon6.material);
        System.out.println("Range: " + weapon6.range);
        System.out.println("Licensed: " + weapon6.isLicensed);
        System.out.println();

        Weapon weapon7 = new Weapon();
        weapon7.weaponId = 7;
        weapon7.type = "Taser";
        weapon7.damage = "Low";
        weapon7.material = "Plastic";
        weapon7.range = "5m";
        weapon7.isLicensed = true;
        System.out.println("Weapon ID: " + weapon7.weaponId);
        System.out.println("Type: " + weapon7.type);
        System.out.println("Damage: " + weapon7.damage);
        System.out.println("Material: " + weapon7.material);
        System.out.println("Range: " + weapon7.range);
        System.out.println("Licensed: " + weapon7.isLicensed);
        System.out.println();

        Weapon weapon8 = new Weapon();
        weapon8.weaponId = 8;
        weapon8.type = "Grenade";
        weapon8.damage = "Explosive";
        weapon8.material = "Metal";
        weapon8.range = "10m";
        weapon8.isLicensed = false;
        System.out.println("Weapon ID: " + weapon8.weaponId);
        System.out.println("Type: " + weapon8.type);
        System.out.println("Damage: " + weapon8.damage);
        System.out.println("Material: " + weapon8.material);
        System.out.println("Range: " + weapon8.range);
        System.out.println("Licensed: " + weapon8.isLicensed);
        System.out.println();

        Weapon weapon9 = new Weapon();
        weapon9.weaponId = 9;
        weapon9.type = "Shotgun";
        weapon9.damage = "High";
        weapon9.material = "Steel";
        weapon9.range = "100m";
        weapon9.isLicensed = true;
        System.out.println("Weapon ID: " + weapon9.weaponId);
        System.out.println("Type: " + weapon9.type);
        System.out.println("Damage: " + weapon9.damage);
        System.out.println("Material: " + weapon9.material);
        System.out.println("Range: " + weapon9.range);
        System.out.println("Licensed: " + weapon9.isLicensed);
        System.out.println();

        Weapon weapon10 = new Weapon();
        weapon10.weaponId = 10;
        weapon10.type = "Spear";
        weapon10.damage = "Medium";
        weapon10.material = "Wood";
        weapon10.range = "Long";
        weapon10.isLicensed = false;
        System.out.println("Weapon ID: " + weapon10.weaponId);
        System.out.println("Type: " + weapon10.type);
        System.out.println("Damage: " + weapon10.damage);
        System.out.println("Material: " + weapon10.material);
        System.out.println("Range: " + weapon10.range);
        System.out.println("Licensed: " + weapon10.isLicensed);
        System.out.println();

        Weapon weapon11 = new Weapon();
        weapon11.weaponId = 11;
        weapon11.type = "Crossbow";
        weapon11.damage = "High";
        weapon11.material = "Aluminum";
        weapon11.range = "250m";
        weapon11.isLicensed = true;
        System.out.println("Weapon ID: " + weapon11.weaponId);
        System.out.println("Type: " + weapon11.type);
        System.out.println("Damage: " + weapon11.damage);
        System.out.println("Material: " + weapon11.material);
        System.out.println("Range: " + weapon11.range);
        System.out.println("Licensed: " + weapon11.isLicensed);
        System.out.println();

        Weapon weapon12 = new Weapon();
        weapon12.weaponId = 12;
        weapon12.type = "Slingshot";
        weapon12.damage = "Low";
        weapon12.material = "Rubber";
        weapon12.range = "30m";
        weapon12.isLicensed = false;
        System.out.println("Weapon ID: " + weapon12.weaponId);
        System.out.println("Type: " + weapon12.type);
        System.out.println("Damage: " + weapon12.damage);
        System.out.println("Material: " + weapon12.material);
        System.out.println("Range: " + weapon12.range);
        System.out.println("Licensed: " + weapon12.isLicensed);
        System.out.println();

        Weapon weapon13 = new Weapon();
        weapon13.weaponId = 13;
        weapon13.type = "Machete";
        weapon13.damage = "Medium";
        weapon13.material = "Steel";
        weapon13.range = "Close";
        weapon13.isLicensed = false;
        System.out.println("Weapon ID: " + weapon13.weaponId);
        System.out.println("Type: " + weapon13.type);
        System.out.println("Damage: " + weapon13.damage);
        System.out.println("Material: " + weapon13.material);
        System.out.println("Range: " + weapon13.range);
        System.out.println("Licensed: " + weapon13.isLicensed);
        System.out.println();

        Weapon weapon14 = new Weapon();
        weapon14.weaponId = 14;
        weapon14.type = "Machine Gun";
        weapon14.damage = "Extreme";
        weapon14.material = "Titanium";
        weapon14.range = "600m";
        weapon14.isLicensed = true;
        System.out.println("Weapon ID: " + weapon14.weaponId);
        System.out.println("Type: " + weapon14.type);
        System.out.println("Damage: " + weapon14.damage);
        System.out.println("Material: " + weapon14.material);
        System.out.println("Range: " + weapon14.range);
        System.out.println("Licensed: " + weapon14.isLicensed);
        System.out.println();

        Weapon weapon15 = new Weapon();
        weapon15.weaponId = 15;
        weapon15.type = "Pepper Spray";
        weapon15.damage = "Irritant";
        weapon15.material = "Plastic";
        weapon15.range = "2m";
        weapon15.isLicensed = true;
        System.out.println("Weapon ID: " + weapon15.weaponId);
        System.out.println("Type: " + weapon15.type);
        System.out.println("Damage: " + weapon15.damage);
        System.out.println("Material: " + weapon15.material);
        System.out.println("Range: " + weapon15.range);
        System.out.println("Licensed: " + weapon15.isLicensed);
        System.out.println();

        Weapon weapon16 = new Weapon();
        weapon16.weaponId = 16;
        weapon16.type = "Bat";
        weapon16.damage = "Blunt";
        weapon16.material = "Wood";
        weapon16.range = "Close";
        weapon16.isLicensed = false;
        System.out.println("Weapon ID: " + weapon16.weaponId);
        System.out.println("Type: " + weapon16.type);
        System.out.println("Damage: " + weapon16.damage);
        System.out.println("Material: " + weapon16.material);
        System.out.println("Range: " + weapon16.range);
        System.out.println("Licensed: " + weapon16.isLicensed);
        System.out.println();

        Weapon weapon17 = new Weapon();
        weapon17.weaponId = 17;
        weapon17.type = "Katana";
        weapon17.damage = "High";
        weapon17.material = "Carbon Steel";
        weapon17.range = "Close";
        weapon17.isLicensed = false;
        System.out.println("Weapon ID: " + weapon17.weaponId);
        System.out.println("Type: " + weapon17.type);
        System.out.println("Damage: " + weapon17.damage);
        System.out.println("Material: " + weapon17.material);
        System.out.println("Range: " + weapon17.range);
        System.out.println("Licensed: " + weapon17.isLicensed);
        System.out.println();

        Weapon weapon18 = new Weapon();
        weapon18.weaponId = 18;
        weapon18.type = "Flamethrower";
        weapon18.damage = "Extreme";
        weapon18.material = "Metal";
        weapon18.range = "20m";
        weapon18.isLicensed = true;
        System.out.println("Weapon ID: " + weapon18.weaponId);
        System.out.println("Type: " + weapon18.type);
        System.out.println("Damage: " + weapon18.damage);
        System.out.println("Material: " + weapon18.material);
        System.out.println("Range: " + weapon18.range);
        System.out.println("Licensed: " + weapon18.isLicensed);
        System.out.println();

        Weapon weapon19 = new Weapon();
        weapon19.weaponId = 19;
        weapon19.type = "Boomerang";
        weapon19.damage = "Low";
        weapon19.material = "Wood";
        weapon19.range = "50m";
        weapon19.isLicensed = false;
        System.out.println("Weapon ID: " + weapon19.weaponId);
        System.out.println("Type: " + weapon19.type);
        System.out.println("Damage: " + weapon19.damage);
        System.out.println("Material: " + weapon19.material);
        System.out.println("Range: " + weapon19.range);
        System.out.println("Licensed: " + weapon19.isLicensed);
        System.out.println();

        Weapon weapon20 = new Weapon();
        weapon20.weaponId = 20;
        weapon20.type = "Bow";
        weapon20.damage = "Medium";
        weapon20.material = "Fiberglass";
        weapon20.range = "150m";
        weapon20.isLicensed = true;
        System.out.println("Weapon ID: " + weapon20.weaponId);
        System.out.println("Type: " + weapon20.type);
        System.out.println("Damage: " + weapon20.damage);
        System.out.println("Material: " + weapon20.material);
        System.out.println("Range: " + weapon20.range);
        System.out.println("Licensed: " + weapon20.isLicensed);
        System.out.println();
    }
}


